services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04  # Exact tag of your locally available image
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Asdqwe123@!
    ports:
      - "1433:1433"
    networks:
      - app-network

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
